service: sls-gcp-ts-boilerplate
frameworkVersion: '3'

provider:
  name: google
  stage: dev
  runtime: nodejs12
  region: us-central1
  project: sls-gcp-ts-boilerplate
  credentials: ~/.gcloud/sls-gcp-ts-boilerplate/keyfile.json

plugins:
  - serverless-google-cloudfunctions
  - serverless-webpack

package:
  include:
    - ./src/index.ts
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - .idea/**

functions:
  random:
    handler: random
    events:
      - http: random
  multiply:
    handler: multiply
    events:
      - http: multiply

custom:
  webpack:
    excludeFiles: src/**/*.test.js
    includeModules: false
    packager: 'npm'
    webpackConfig: 'webpack.config.js'
